---
- name: Create document roots
  file: path={{item.documentroot}} owner=www-data group=www-data state=directory recurse=yes
  with_items: "{{ apache_vhosts + apache_vhosts_ssl }}"

- name: Create php tmp dir
  file: path={{ php_tmp }} owner=www-data group=www-data state=directory

- name: Create apache rules directory
  file: path=/etc/apache2/rules owner=root group=root state=directory recurse=yes

- name: Copy rules file
  copy: src={{item.src}} dest=/etc/apache2/rules/{{item.name}} owner=root group=root
  with_items: apache_rules
