---

- name: Stat document roots
  stat: path={{item.documentroot}}
  register: document_root_stats
  with_items: "{{ apache_vhosts + apache_vhosts_ssl }}"

- name: Create document roots
  file: path={{item.0.documentroot}} owner=www-data group=www-data state=directory recurse=yes
  when: item.1.stat.exists is defined and item.1.stat.exists != True
  with_together:
    - "{{ apache_vhosts + apache_vhosts_ssl }}"
    - document_root_stats

- name: Create php tmp dir
  file: path={{ php_tmp }} owner=www-data group=www-data state=directory

- name: Create apache rules directory
  file: path=/etc/apache2/rules owner=root group=root state=directory recurse=yes

- name: Copy rules file
  copy: src={{item.src}} dest=/etc/apache2/rules/{{item.name}} owner=root group=root
  with_items: apache_rules
